# reloading datasets: original, preprocess & transformed:

In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# from sklearn.model_selection import train_test_split

# %load_ext autoreload
# %autoreload 2
# import FusionModel_tools as fm
# import importlib
# importlib.reload(fm)

# import nltk
# nltk.download('popular', quiet = True)

import os
import time


In [2]:
## define general parameters

myseed = 123

splitting_path = '../Splitted_datasets/'
preprocessing_path = '../Preprocessed_data/'
training_path = '../Trained_models_and_metrics/'


## original: splitings

In [3]:
df_X_train = pd.read_csv(splitting_path + '2308141811_df_X_train.csv', index_col = 0, header = 0)
df_X_test = pd.read_csv(splitting_path + '2308141811_df_X_test.csv', index_col = 0, header = 0)
df_y_train = pd.read_csv(splitting_path + '2308141811_df_y_train.csv', index_col = 0, header = 0)
df_y_test = pd.read_csv(splitting_path + '2308141811_df_y_test.csv', index_col = 0, header = 0)

In [4]:
print(df_X_train.index)
df_X_train.head()

Int64Index([ 9263, 50884, 73788, 34901, 81204, 26065, 46256, 70161, 24947,
            32350,
            ...
            29427,  6336, 69930, 71944, 18110, 19372, 79662, 38386, 84570,
            60763],
           dtype='int64', length=67932)


designation  \
9263                   Lot 3 Livres - Contes Merveilleux   
50884        Amiibo Splatoon Calamar Inkling Violet Néon   
73788  Atterrissage Prolongée Vitesse De Jambe D'appu...   
34901              Rideau D'ameublement À Effet Chenille   
81204                Porte-Cartes De Visites Magnetoplan   

                                             description   productid  \
9263                                                 NaN  3618603061   
50884                                                NaN  1997652852   
73788  NOUVEAU Landing Gear Extended Leg support Prot...  4197675553   
34901  Rideau de 140 x 260 cm qui saura mettre en ava...  3601180051   
81204  magnetoplan porte-cartes de visite transparent...   278813457   

          imageid  
9263   1228606644  
50884  1119376033  
73788  1313430830  
34901  1226564377  
81204   977811081

In [5]:
print(df_X_test.index)
df_X_test.head()

Int64Index([76291, 35651, 23689, 27954, 53964, 25569,   462, 76121, 81032,
            80184,
            ...
            43294, 23597, 28244,  7725, 20720, 84173, 53364, 62653, 33334,
            83750],
           dtype='int64', length=16984)


designation  \
76291    Fullmetal Alchemist Figurine Riza Hawkeye 10 Cm   
35651              Mebby Biberon Vetro 270ml Lattice Blu   
23689  Chaise De Plage Hwc-A11 Mer Du Nord Bâche Incl...   
27954  Mini Fc 129 Console De Jeu Vidéo Rétro Jeu Min...   
53964  Brosses à lamelles R9022 Zodiac Vortex 4 - La ...   

                                             description   productid  \
76291  Trading figurine d'une taille de 10 cm environ...   304773553   
35651                                                NaN  1233521151   
23689  Chaise de plage HWC-A11 mer du Nord bâche incl...  3738732335   
27954  Numéro du modèle:Handheld retro Players<br />A...  4200877059   
53964  Utilisation des brosses à lamelles R9022 Zodia...   207257892   

          imageid  
76291   996061500  
35651  1233288653  
23689  1239669685  
27954  1316192545  
53964   941677156

In [6]:
print(df_y_train.index)
df_y_train.head()

Int64Index([ 9263, 50884, 73788, 34901, 81204, 26065, 46256, 70161, 24947,
            32350,
            ...
            29427,  6336, 69930, 71944, 18110, 19372, 79662, 38386, 84570,
            60763],
           dtype='int64', length=67932)


prdtypecode
9263          2403
50884           50
73788         1300
34901         1920
81204         2522

In [7]:
print(df_y_test.index)
df_y_test.head()

Int64Index([76291, 35651, 23689, 27954, 53964, 25569,   462, 76121, 81032,
            80184,
            ...
            43294, 23597, 28244,  7725, 20720, 84173, 53364, 62653, 33334,
            83750],
           dtype='int64', length=16984)


prdtypecode
76291         1140
35651         1320
23689         2582
27954           60
53964         2583

## preprocessed dataset: X

In [8]:
df_X_train_preprocess = pd.read_csv(preprocessing_path+'2308141824_df_X_train_preprocess.csv', header = 0, index_col = 0, sep = ',')
df_X_test_preprocess = pd.read_csv(preprocessing_path+'2308141824_df_X_test_preprocess.csv', header = 0, index_col = 0, sep = ',')
# df_y_train = pd.read_csv( splitting_path+'2308121827_df_y_train.csv', header = 0, index_col = 0, sep = ',')
# df_y_test = pd.read_csv( splitting_path+'2308121827_df_y_test.csv', header = 0, index_col = 0, sep = ',')

In [9]:
print(df_X_train_preprocess.index)
df_X_train_preprocess.head()

Int64Index([ 9263, 50884, 73788, 34901, 81204, 26065, 46256, 70161, 24947,
            32350,
            ...
            29427,  6336, 69930, 71944, 18110, 19372, 79662, 38386, 84570,
            60763],
           dtype='int64', length=67932)


title  \
9263                   Lot 3 Livres - Contes Merveilleux   
50884        Amiibo Splatoon Calamar Inkling Violet Néon   
73788  Atterrissage Prolongée Vitesse De Jambe D'appu...   
34901              Rideau D'ameublement À Effet Chenille   
81204                Porte-Cartes De Visites Magnetoplan   

                                             description   productid  \
9263                                                 NaN  3618603061   
50884                                                NaN  1997652852   
73788  NOUVEAU Landing Gear Extended Leg support Prot...  4197675553   
34901  Rideau de 140 x 260 cm qui saura mettre en ava...  3601180051   
81204  magnetoplan porte-cartes de visite transparent...   278813457   

          imageid                                        title_descr  \
9263   1228606644              lot 3 livres - contes merveilleux \n    
50884  1119376033    amiibo splatoon calamar inkling violet néon \n    
73788  1313430830  atterrissage prolongée vitesse de jambe d'appu...   
34901  1226564377  rideau d'ameublement à effet chenille \n ridea...   
81204   977811081  porte-cartes de visites magnetoplan \n magneto...   

                                            lemma_tokens language  \
9263          ['lot', 'livres', 'contes', 'merveilleux']       fr   
50884  ['amiibo', 'splatoon', 'calamar', 'inkling', '...       en   
73788  ['atterrissage', 'prolongée', 'vitesse', 'jamb...       fr   
34901  ['rideau', 'ameublement', 'chenille', '140', '...       fr   
81204  ['porte', 'carte', 'visites', 'magnetoplan', '...       fr   

       text_token_len  
9263                4  
50884               6  
73788              54  
34901              66  
81204               8

In [10]:
print(df_X_test_preprocess.index)
df_X_test_preprocess.head()

Int64Index([76291, 35651, 23689, 27954, 53964, 25569,   462, 76121, 81032,
            80184,
            ...
            43294, 23597, 28244,  7725, 20720, 84173, 53364, 62653, 33334,
            83750],
           dtype='int64', length=16984)


title  \
76291    Fullmetal Alchemist Figurine Riza Hawkeye 10 Cm   
35651              Mebby Biberon Vetro 270ml Lattice Blu   
23689  Chaise De Plage Hwc-A11 Mer Du Nord Bâche Incl...   
27954  Mini Fc 129 Console De Jeu Vidéo Rétro Jeu Min...   
53964  Brosses à lamelles R9022 Zodiac Vortex 4 - La ...   

                                             description   productid  \
76291  Trading figurine d'une taille de 10 cm environ...   304773553   
35651                                                NaN  1233521151   
23689  Chaise de plage HWC-A11 mer du Nord bâche incl...  3738732335   
27954  Numéro du modèle:Handheld retro Players<br />A...  4200877059   
53964  Utilisation des brosses à lamelles R9022 Zodia...   207257892   

          imageid                                        title_descr  \
76291   996061500  fullmetal alchemist figurine riza hawkeye 10 c...   
35651  1233288653          mebby biberon vetro 270ml lattice blu \n    
23689  1239669685  chaise de plage hwc-a11 mer du nord bâche incl...   
27954  1316192545  mini fc 129 console de jeu vidéo rétro jeu min...   
53964   941677156  brosses à lamelles r9022 zodiac vortex 4 - la ...   

                                            lemma_tokens language  \
76291  ['fullmetal', 'alchemist', 'figurine', 'riza',...       fr   
35651  ['mebby', 'biberon', 'vetro', '270ml', 'lattic...       en   
23689  ['chaise', 'plage', 'hwc', 'a11', 'mer', 'nord...       fr   
27954  ['mini', '129', 'console', 'jeu', 'vidéo', 'ré...       fr   
53964  ['brosses', 'lamelles', 'r9022', 'zodiac', 'vo...       fr   

       text_token_len  
76291               8  
35651               6  
23689             143  
27954              39  
53964              16

## Transformed data

In [11]:
from scipy import sparse

text_data = {}

text_data['X_train'] = sparse.load_npz("../Preprocessed_data/2308141825_text_data_transformed_X_train.npz")
text_data['X_test'] = sparse.load_npz("../Preprocessed_data/2308141825_text_data_transformed_X_test.npz")


In [12]:
print(text_data['X_train'].shape)
text_data['X_train'].toarray()[14,:25]


(67932, 5035)


array([0.02524272, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [13]:
print(text_data['X_test'].shape)
text_data['X_test'].toarray()[14,:25]

(16984, 5035)


array([0.09320388, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 1.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

**Targets**

In [14]:
targets = {}
targets['y_train'] = np.load("../Preprocessed_data/2308141825_text_data_transformed_y_train.npy")
targets['y_test'] = np.load("../Preprocessed_data/2308141825_text_data_transformed_y_test.npy")

In [15]:
print(targets['y_train'].shape)
print(targets['y_train'][:5,:])
print(targets['y_train'][:5,:].argmax(axis = 1))

(67932, 27)
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]]
[19  2  9 14 21]


In [16]:
print(targets['y_test'].shape)
print(targets['y_test'][:5,:])
print(targets['y_test'][:5,:].argmax(axis = 1))

(16984, 27)
[[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]]
[ 4 12 22  3 23]


**Transformers**

In [17]:
import joblib

token_len_scaler = joblib.load("../Preprocessed_data/2308141825_token_len_scaler")
language_encoder = joblib.load("../Preprocessed_data/2308141825_language_encoder")
lemmas_vectorizer = joblib.load("../Preprocessed_data/2308141825_lemmas_vectorizer")
target_encoder = joblib.load("../Preprocessed_data/2308141825_target_encoder")

In [18]:
print(token_len_scaler.data_min_)
print(token_len_scaler.data_max_)
print(token_len_scaler.scale_)
print(token_len_scaler.n_features_in_)
print(token_len_scaler.n_samples_seen_)
print(token_len_scaler.feature_names_in_)

[0.]
[515.]
[0.00194175]
1
67932
['text_token_len']


In [19]:
print(language_encoder.categories_)
print(language_encoder.n_features_in_)
print(language_encoder.feature_names_in_)

[array(['af', 'an', 'br', 'ca', 'cy', 'da', 'de', 'en', 'eo', 'es', 'et',
       'eu', 'fi', 'fr', 'ga', 'ht', 'hu', 'id', 'it', 'jv', 'la', 'lb',
       'lt', 'mg', 'nl', 'no', 'oc', 'pl', 'pt', 'qu', 'ro', 'sw', 'tl',
       'wa'], dtype=object)]
1
['language']


In [20]:
print(len(lemmas_vectorizer.vocabulary_),'\n')
print(dict(list(lemmas_vectorizer.vocabulary_.items() )[:25]),'\n' )
print(list(lemmas_vectorizer.stop_words_)[:25])

5000 

{'lot': 2751, 'livres': 2731, 'merveilleux': 2896, 'violet': 4773, 'atterrissage': 632, 'prolongée': 3663, 'vitesse': 4785, 'appui': 541, 'protector': 3681, 'extension': 1907, 'dji': 1575, 'pro': 3628, 'mavic': 2872, 'générique': 2282, 'landing': 2635, 'gear': 2185, 'support': 4379, 'description': 1495, '100': 7, 'neuf': 3100, 'haute': 2307, 'qualité': 3756, 'augmente': 642, 'sécurité': 4413, 'hauteur': 2310} 

['19x4x7cm', 'itanti', '6970audio', 'rac', 'gt4', 'n1kc', '0029échelle', '250v', '14x7x9cm', '2v80mahbattery', 'calomnies', 'visualeffects', 'déverrouille', 'ecw', 'a51', 'grandmont', 'ventilécorps', 'naissant', 'kitchenhpp13726', '11227909920', 'gustave', 'heuresapplicable', 'flybest', 'astralle', 'réservée']


In [21]:
print(target_encoder.classes_)

[  10   40   50   60 1140 1160 1180 1280 1281 1300 1301 1302 1320 1560
 1920 1940 2060 2220 2280 2403 2462 2522 2582 2583 2585 2705 2905]


## image data preprocessed
Computed for each item in "df_X_train_preprocess" and "df_X_test_preprocess".  
So indexes belong to these dataframes

In [22]:
image_train_preprocess = np.load("../Preprocessed_data/2308141850_df_image_train_preprocess.npy")
image_test_preprocess = np.load("../Preprocessed_data/2308141850_df_image_test_preprocess.npy")

In [25]:
print(image_train_preprocess.shape)
print(image_train_preprocess[0,:50])

(67932, 30000)
[255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 255 255 255 255 255 255 255 255 255 255 255 255 251 255 254 255 248 255
  48  42  99  50  44 115  57  52 121  45  41 107  39  41]


In [46]:
## train images idexes
print(list(df_X_train_preprocess.index)[:50])

[9263, 50884, 73788, 34901, 81204, 26065, 46256, 70161, 24947, 32350, 38334, 13255, 74781, 26466, 67566, 62073, 10878, 78873, 54625, 72433, 19434, 31164, 64340, 11740, 16505, 26723, 46990, 27898, 13313, 10332, 8445, 36349, 44167, 44392, 79117, 19289, 7975, 1532, 45923, 42445, 31657, 17914, 29574, 44309, 51061, 46774, 41479, 31, 30602, 78871]


In [45]:
print(image_test_preprocess.shape)
print(image_test_preprocess[3535,:50])

(16984, 30000)
[255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255
 255 255 255 255 255 255 255 255 255 255 255 255 253 255 255 255 255 251
 116 136 161  94 124 159  90 117 151  95 116 147  76 103]


In [47]:
## train images idexes
print(list(df_X_test_preprocess.index)[:50])

[76291, 35651, 23689, 27954, 53964, 25569, 462, 76121, 81032, 80184, 55236, 37176, 39826, 38238, 71212, 19785, 8964, 84720, 24405, 30751, 81304, 6922, 67037, 46196, 79995, 27693, 45397, 7546, 38960, 63984, 20123, 25096, 5784, 42674, 10532, 27063, 25947, 78713, 21406, 61376, 71897, 75174, 38954, 50284, 8624, 81739, 78115, 78261, 68455, 56559]


## image data transformed

In [ ]:
t0 = time.time()

image_train_transformed = np.load("../Preprocessed_data/2308141953_image_train_transformed.npz")['array']
image_test_transformed = np.load("../Preprocessed_data/2308141953_image_test_transformed.npz")['array']

t1 = time.time()
print("Loading arrays takes %0.2f seconds" %(t1-t0))

Loading arrays takes 47.08 seconds


In [52]:
print(image_train_transformed.shape)
print(image_train_transformed[0,0,:50,0])

(67932, 100, 100, 3)
[1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         0.98431373 1.
 0.18823529 0.19607843 0.22352941 0.17647059 0.15294118 0.14509804
 0.16862745 0.18431373 0.17254902 0.15686275 0.18431373 0.21568627
 0.22352941 0.21176471 0.21176471 0.17254902 0.24705882 0.23529412
 0.19215686 0.17647059 0.21176471 0.22352941 0.19215686 0.21960784
 0.20392157 0.2627451  0.23529412 0.23921569 0.23921569 0.23137255
 0.28235294 0.30980392 0.33333333 0.28627451 0.28627451 0.28627451
 0.25490196 0.23137255]


In [54]:
print(image_test_transformed.shape)
print(image_test_transformed[0,0,:50,0])

(16984, 100, 100, 3)
[1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         1.
 1.         1.         1.         1.         1.         0.99607843
 1.         0.98431373 0.85098039 0.79607843 0.80784314 0.80784314
 0.80784314 0.80784314 0.80784314 0.80784314 0.80784314 0.80784314
 0.80784314 0.80784314 0.80784314 0.80784314 0.80784314 0.80784314
 0.80784314 0.80392157 0.80392157 0.80392157 0.80784314 0.80392157
 0.8        0.79607843]
